# for running tests docker-compose up --build --exit-code-from esexecutor
# for development docker-compose up --build
version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.2
    ports:
    - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
  searcher:
    container_name: searcher
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    command: ["./wait-for-es.sh", "http://elasticsearch:9200", "tail", "-f", "/dev/null"]
    working_dir: "/src"
    volumes:
      - ./src:/src